import * as fs from "fs/promises";
import * as path from "path";

import * as os from "os";

interface ProjectMetadata {
  name: string;
  description: string;
  createdAt: string;
  conventions: {
    namingStyle: "camelCase" | "PascalCase" | "snake_case";
  };
}

export class MarkdownProjectStore {
  private projectRoot: string | null = null;

  // Initialize/create a new project
  async initProject(name: string, description: string) {
    const tempDir = path.join(
      os.homedir(),
      "Documents",
      "mcp-thesis-projects",
      "projects"
    );

    const projectPath = path.join(tempDir, name);
    this.projectRoot = projectPath;

    // Create project structure
    await fs.mkdir(projectPath, { recursive: true });
    await fs.mkdir(path.join(projectPath, "use-cases"), { recursive: true });
    await fs.mkdir(path.join(projectPath, "diagrams"), { recursive: true });
    await fs.mkdir(path.join(projectPath, "entities"), { recursive: true });

    // Create project metadata file
    const metadata: ProjectMetadata = {
      name,
      description,
      createdAt: new Date().toISOString(),
      conventions: {
        namingStyle: "PascalCase",
      },
    };

    const readmeMd = `# ${name}

${description}

**Created:** ${new Date().toLocaleDateString()}

## Project Structure

\`\`\`
${path.basename(projectPath)}/
├── README.md           # This file
├── project.json        # Project metadata
├── use-cases/          # Use case descriptions
├── diagrams/           # Generated PlantUML diagrams
│   ├── use-case.md
│   ├── sequence/
│   └── class.md
└── entities/           # Extracted entities
    ├── actors.md
    ├── systems.md
    └── classes.md
\`\`\`

## Usage

1. Add use cases to \`use-cases/\` directory
2. Run tools to extract entities and generate diagrams
3. All diagrams are stored in \`diagrams/\` with consistent naming
`;

    await fs.writeFile(path.join(projectPath, "README.md"), readmeMd);
    await fs.writeFile(
      path.join(projectPath, "project.json"),
      JSON.stringify(metadata, null, 2)
    );

    // Initialize entity files
    await fs.writeFile(
      path.join(projectPath, "entities", "actors.md"),
      "# Actors\n\n"
    );
    await fs.writeFile(
      path.join(projectPath, "entities", "systems.md"),
      "# Systems\n\n"
    );
    await fs.writeFile(
      path.join(projectPath, "entities", "classes.md"),
      "# Classes\n\n"
    );

    return projectPath;
  }

  // Load existing project
  async loadProject(projectPath: string) {
    try {
      await fs.access(path.join(projectPath, "project.json"));
      this.projectRoot = projectPath;
      return true;
    } catch {
      return false;
    }
  }

  getProjectRoot(): string | null {
    return this.projectRoot;
  }

  // Read entities from markdown files
  async readEntities(
    type: "actors" | "systems" | "classes"
  ): Promise<string[]> {
    if (!this.projectRoot) return [];

    try {
      const content = await fs.readFile(
        path.join(this.projectRoot, "entities", `${type}.md`),
        "utf-8"
      );

      // Extract list items
      const matches = content.match(/^- (.+)$/gm);
      return matches ? matches.map((m) => m.replace(/^- /, "").trim()) : [];
    } catch {
      return [];
    }
  }

  // Write entities to markdown files
  async writeEntities(
    type: "actors" | "systems" | "classes",
    entities: string[]
  ) {
    if (!this.projectRoot) return;

    const uniqueEntities = [...new Set(entities)].sort();
    const content = `# ${type.charAt(0).toUpperCase() + type.slice(1)}

${uniqueEntities.map((e) => `- ${e}`).join("\n")}

---
*Last updated: ${new Date().toISOString()}*
`;

    await fs.writeFile(
      path.join(this.projectRoot, "entities", `${type}.md`),
      content
    );
  }

  // Add entity (read, append, write)
  async addEntity(type: "actors" | "systems" | "classes", entity: string) {
    const existing = await this.readEntities(type);
    if (!existing.includes(entity)) {
      existing.push(entity);
      await this.writeEntities(type, existing);
    }
  }

  // Save use case as markdown
  async saveUseCase(
    id: string,
    title: string,
    content: string,
    extracted: any
  ) {
    if (!this.projectRoot) return;

    const markdown = `# ${title}

**ID:** ${id}  
**Created:** ${new Date().toISOString()}

## Description

${content}

## Extracted Entities

### Actors
${extracted.actors.map((a: string) => `- ${a}`).join("\n")}

### Systems
${extracted.systems.map((s: string) => `- ${s}`).join("\n")}

### Potential Classes
${extracted.classes.map((c: string) => `- ${c}`).join("\n")}

---
*Auto-generated by MCP UML Server*
`;

    await fs.writeFile(
      path.join(this.projectRoot, "use-cases", `${id}.md`),
      markdown
    );
  }

  // Read all use cases
  async readAllUseCases(): Promise<Array<{ id: string; content: string }>> {
    if (!this.projectRoot) return [];

    try {
      const files = await fs.readdir(path.join(this.projectRoot, "use-cases"));
      const useCases = [];

      for (const file of files) {
        if (file.endsWith(".md")) {
          const content = await fs.readFile(
            path.join(this.projectRoot, "use-cases", file),
            "utf-8"
          );
          useCases.push({
            id: file.replace(".md", ""),
            content,
          });
        }
      }

      return useCases;
    } catch {
      return [];
    }
  }

  // Save diagram as markdown with embedded PlantUML
  async saveDiagram(type: string, plantuml: string, metadata?: any) {
    if (!this.projectRoot) return;

    const markdown = `# ${type.charAt(0).toUpperCase() + type.slice(1)} Diagram

**Generated:** ${new Date().toISOString()}

${
  metadata
    ? `## Metadata\n\n\`\`\`json\n${JSON.stringify(
        metadata,
        null,
        2
      )}\n\`\`\`\n\n`
    : ""
}

## PlantUML Code

\`\`\`plantuml
${plantuml}
\`\`\`

## Visualization

To view this diagram:
1. Copy the PlantUML code above
2. Paste into https://www.plantuml.com/plantuml/uml/
3. Or use PlantUML extension in VS Code

---
*Auto-generated by MCP UML Server*
`;

    const diagramPath = type.includes("/")
      ? path.join(this.projectRoot, "diagrams", type + ".md")
      : path.join(this.projectRoot, "diagrams", `${type}.md`);

    // Ensure directory exists
    await fs.mkdir(path.dirname(diagramPath), { recursive: true });
    await fs.writeFile(diagramPath, markdown);
  }

  // Read project metadata
  async readMetadata(): Promise<ProjectMetadata | null> {
    if (!this.projectRoot) return null;

    try {
      const content = await fs.readFile(
        path.join(this.projectRoot, "project.json"),
        "utf-8"
      );
      return JSON.parse(content);
    } catch {
      return null;
    }
  }

  // Get project summary
  async getProjectSummary() {
    if (!this.projectRoot) return null;

    const metadata = await this.readMetadata();
    const actors = await this.readEntities("actors");
    const systems = await this.readEntities("systems");
    const classes = await this.readEntities("classes");
    const useCases = await this.readAllUseCases();

    return {
      metadata,
      entities: {
        actors: actors.length,
        systems: systems.length,
        classes: classes.length,
      },
      useCases: useCases.length,
      path: this.projectRoot,
    };
  }
}
