import { z } from "zod";

/**
 * Zod schema for GenStep - individual step in a use case flow
 */
export const genStepSchema = z.object({
  index: z.number().int().positive(),
  actor: z.string().min(1),
  target: z.string().optional(),
  description: z.string().min(1),
});

/**
 * Zod schema for GenFlow - flow structure (MAIN, ALTERNATIVE, EXCEPTION)
 */
export const genFlowSchema = z.object({
  id: z.string().min(1),
  kind: z.enum(["MAIN", "ALTERNATIVE", "EXCEPTION"]),
  parentFlow: z.string().optional(),
  fromStepIndex: z.number().int().positive().optional(),
  condition: z.string().optional(),
  steps: z.array(genStepSchema).min(1),
});

/**
 * Zod schema for GenLoop - loop structure in a flow
 */
export const genLoopSchema = z.object({
  flowRef: z.string().min(1),
  startIndex: z.number().int().positive(),
  endIndex: z.number().int().positive(),
  condition: z.string().min(1),
});

/**
 * Main Zod schema for GenUseCase
 * Validates the complete use case structure generated by Gemini or other sources
 */
export const genUseCaseSchema = z.object({
  name: z.string().min(1),
  summary: z.string().min(1),
  mainActor: z.string().min(1),
  actors: z.array(z.string().min(1)).min(1),
  preconditions: z.array(z.string()).optional(),
  postconditions: z.array(z.string()).optional(),
  flows: z.array(genFlowSchema).min(1),
  loops: z.array(genLoopSchema).optional(),
});

/**
 * Type inference from the Zod schema
 */
export type GenUseCaseSchemaType = z.infer<typeof genUseCaseSchema>;
export type GenFlowSchemaType = z.infer<typeof genFlowSchema>;
export type GenStepSchemaType = z.infer<typeof genStepSchema>;
export type GenLoopSchemaType = z.infer<typeof genLoopSchema>;
